import benzbanner from '../assets/dataimages/benz.png';
import paysafe from '../assets/dataimages/Paysafe.png';
// import nobroker from '../assets/dataimages/NoBroker.png';
// import cisco from '../assets/dataimages/Cisco.png';
// import cluster from '../assets/dataimages/benz.png';

export const caseStudyCardDataDummy = [
  {
    'Web App': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
  {
    'Mobile App': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'benzbanner',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'nobroker',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
  {
    'HMI Design': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'benzbanner',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'nobroker',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
  {
    'Design System': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'benzbanner',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'nobroker',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
  {
    'Heuristic Evaluation': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'benzbanner',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'nobroker',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
  {
    'Usability Testing': {
      caseStudyLg: [
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: benzbanner,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: paysafe,
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'benzbanner',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'amg-driving-academy',
        },
        {
          insight: true,
          insight1: '5%',
          insight1Desc: 'Increase in resume building',
          insight2: '5%',
          insight2Desc: 'Increase in resume building',
          title: 'The Psychology Behind Effective UX Design',
          description:
            'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
          position: 'Lead Designer',
          client: 'ge',
          tools: '8 min',
          imgSrc: 'nobroker',
          link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
          pathName: 'psychology-of-ux',
        },
      ],
    },
  },
];

// const caseStudyCardsData = {
//     caseStudyLg: [
//       {
//         insight: true,
//         insight1: '5%',
//         insight1Desc: 'Increase in resume building',
//         insight2: '5%',
//         insight2Desc: 'Increase in resume building',
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Lead Designer',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: benzbanner,
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'amg-driving-academy',
//       },
//       {
//         insight: true,
//         insight1: '5%',
//         insight1Desc: 'Increase in resume building',
//         insight2: '5%',
//         insight2Desc: 'Increase in resume building',
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Lead Designer',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: paysafe,
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'psychology-of-ux',
//       },
//       {
//         insight: true,
//         insight1: '5%',
//         insight1Desc: 'Increase in resume building',
//         insight2: '5%',
//         insight2Desc: 'Increase in resume building',
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Lead Designer',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: 'benzbanner',
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'amg-driving-academy',
//       },
//       {
//         insight: true,
//         insight1: '5%',
//         insight1Desc: 'Increase in resume building',
//         insight2: '5%',
//         insight2Desc: 'Increase in resume building',
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Lead Designer',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: 'nobroker',
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'psychology-of-ux',
//       },
//     ],
//     caseStudySm: [
//       {
//         insight: false,
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Nov 5, 2023',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc:
//           'https://media.nngroup.com/static/img/banners/home-consulting_2x.webp',
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'e-commerce-optimization',
//       },
//       {
//         insight: false,
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Nov 5, 2023',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc:
//           'https://media.nngroup.com/static/img/banners/home-consulting_2x.webp',
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'mobile-app-design',
//       },
//     ],
//     caseStudyXs: [
//       {
//         insight: false,
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Nov 5, 2023',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: nobroker,
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'e-commerce-optimization',
//       },
//       {
//         insight: false,
//         title: 'The Psychology Behind Effective UX Design',
//         description:
//           'Explore the cognitive principles that make certain user interfaces intuitive and satisfying while others frustrate users. Learn how to apply psychological insights to create more engaging digital experiences.',
//         position: 'Nov 5, 2023',
//         client: 'ge',
//         tools: '8 min',
//         imgSrc: nobroker,
//         link: 'https://open.substack.com/pub/praveenmanchi/p/amg-driving-academy-case-study?r=4yhy4f&utm_campaign=post&utm_medium=web&showWelcomeOnShare=false',
//         pathName: 'mobile-app-design',
//       },
//     ],
//   };
